DROP TABLE IF EXISTS hits;

CREATE TABLE IF NOT EXISTS hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(512)                            NOT NULL,
    uri       VARCHAR(512)                            NOT NULL,
    ip        VARCHAR(512)                            NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE                NOT NULL,
                            CONSTRAINT pk_hits PRIMARY KEY (id)
    );